/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.CheckAll;
import model.ConnectDB;
import model.Constant;
import model.Faculty;

/*  Description: Chương trình quản lý sinh viên
 *  Author: Đổng Kiến Lợi
 *  Email: kienloi10@gmail.com
 *  Date: 10/08/2018
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form DangKy
     */
    ConnectDB connect = new ConnectDB();
    CheckAll checkAll = new CheckAll();
    List<Faculty> arrayList = new ArrayList<Faculty>();

    //private List<Faculty> faculty = new List<Faculty>();
    public Register() {
        initComponents();    
        setLocationRelativeTo(this);
        setResizable(false);
        connect.getConnect();
        showComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lb_Name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordCF = new javax.swing.JPasswordField();
        cbFaculty = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_Name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb_Name.setText("ĐĂNG KÝ TÀI KHOẢN");

        jLabel1.setText("Tên đăng nhập");

        jLabel2.setText("Mật khẩu");

        jLabel3.setText("Xác nhận mật khẩu");

        jLabel4.setText("Khoa");

        cbFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFacultyActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(txtPassword)
                            .addComponent(txtPasswordCF)
                            .addComponent(cbFaculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnOK)
                        .addGap(59, 59, 59)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Name)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPasswordCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
        Name: showComboBox
        Description: Show info name faculty in combobox
        Return: null
        Parameter: null
    */
    public void showComboBox(){
        arrayList = connect.getFaculty();
        for(int i = 0; i < arrayList.size(); i++)
        {
            cbFaculty.addItem(arrayList.get(i).getNameFaculty());
        }
        
    }
    
    
    
    /*
        Name: btnCancelActionPerformed
        Description: Execute when click button
        Return: null
        Parameter: java.awt.event.ActionEvent evt - event when click button
    */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here
        Login lg = new Login();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /*
        Name checkConfirmPass
        Description: Check password and Confirm password
        Return: True/False
        Parameter:  String passA
        Parameter:  String passB
    */
    private boolean checkConfirmPass(String passA, String passB)
    {
        boolean result = false;
        if (passA.equals(passB.trim()))
        {
            result = true;
        }
        return result;
    }
    /*
        Name: btnCancelActionPerformed
        Description: Execute when click button
        Return: null
        Parameter: java.awt.event.ActionEvent evt - event 
        2.a.1, 2.a.2, 2.a.3, 2.a.4, 2.a.7, 2.a.6
        (2) Xử lý đăng nhập					
        2. Xử lý check			
        a. Check hạng mục					

    */
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        
        String userNameR = txtUsername.getText().trim();
        String passwordR = new String(txtPassword.getPassword());        
        String passwordRCF = new String(txtPasswordCF.getPassword());
        String faculty = (String)cbFaculty.getSelectedItem();
        // Check hạng mục 1
        if (checkAll.checkEmpty(userNameR) || checkAll.checkEmpty(passwordR) || checkAll.checkEmpty(passwordRCF)){ //check empty
            JOptionPane.showMessageDialog(null, Constant.REGISTER_EMPTY);
        }else{
            if (checkConfirmPass(passwordR, passwordRCF) == false)      //Check pass and confirm password
            {
                JOptionPane.showMessageDialog(null, Constant.REGISTER_E001);
            }else{
                if (checkAll.checkSpecialValue(userNameR) == true){ //Check special value
                    JOptionPane.showMessageDialog(null, Constant.REGISTER_E003);
                }else{
                    if (checkAll.checkLength(userNameR) == true){   //Check length
                        JOptionPane.showMessageDialog(null, Constant.REGISTER_E004);
                    }else{
                        connect.getConnect();
                        connect.addUser(userNameR, passwordR, faculty);
                    }
                }
                
                
            }
        }
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void cbFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFacultyActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbFaculty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_Name;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordCF;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
